### PR TITLE
Add Questions and References for Chapter 4 Third 1

### PR DESCRIPTION
**Pull request by davidhsonic**

### CODE REVIEW

**Comment by davidhsonic** [comment]
@AbhiJohal and @LukasNilsson Here is my PR.

**Comment by AbhiJohal** [comment]
The questions look fine. I'd say be more expressive with the headings, using hierarchy of headings with different number of '#'s. But that's more of a design preference, really. 
I don't see any references in there. If you're masking references as questions, make sure to specify that.

**Comment by AbhiJohal** [comment]
And I apologize for the late review. I will make sure that I remain on schedule for the next time.

**Comment by LukasNilsson** [comment]
Thumbs up

**Pull request merged**
